---
app:
  id: read-only
  name: Read Only Service
  log-level: trace

grpc:
  ip: 0.0.0.0
  port: 30002

writer:
  ip: 0.0.0.0
  port: 30001

postgresql:
  host: 0.0.0.0
  port: "5438"
  username: master_user
  database: master_db
  password: 031501
